stages:
  - build
  - publish

include:
  - project: 'alpine/infra/gitlab-ci-templates'
    ref: master
    file: '/exec/docker-image-base.yml'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

.rules:publish:
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME =~ /.*-stable$/

.component:gitlab-shell:
  variables:
    COMPONENT: gitlab-shell
    PUBLISH_CI_IMAGE: YesPlease
    MIRROR_DOCKER_HUB: YesPlease
    EXEC_SH: YesPlease
  script:
    - source ./VERSIONS
    - source ./build-args.env
    - export ARG_ALPINE_VERSION=$ALPINE_VERSION
    - export ARG_GITLAB_SHELL_VERSION=$GITLAB_SHELL_VERSION
    - export DOCKER_TAG=$GITLAB_SHELL_VERSION
    - install -Dm0644 lib/* -t gitlab-shell/build/lib/
    - entrypoint

build:gitlab-shell:
  extends: [.build-image, .component:gitlab-shell]
  stage: build
  variables:
    EXEC_COMMAND: build
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "false" || $CI_MERGE_REQUEST_IID
      changes:
        paths:
          - .gitlab-ci.yml
          - overlay/**/*
          - gitlab-shell/**/*
          - lib/**/*
          - build-args.env
          - VERSIONS

publish:gitlab-shell:
  extends: [.build-image, .rules:publish, .component:gitlab-shell]
  stage: publish
  variables:
    EXEC_COMMAND: publish

publish:gitlab-shell-next:
  extends: [.build-image, .component:gitlab-shell]
  stage: publish
  variables:
    EXEC_COMMAND: publish
    DOCKER_TAG: next
  rules:
    - if: $CI_COMMIT_REF_NAME == "next"

.component:gitaly:
  variables:
    COMPONENT: gitaly
    PUBLISH_CI_IMAGE: YesPlease
    MIRROR_DOCKER_HUB: YesPlease
    EXEC_SH: YesPlease
  script:
    - source ./VERSIONS
    - source ./build-args.env
    - export ARG_ALPINE_VERSION=$ALPINE_VERSION
    - export ARG_RUBY_VERSION=$RUBY_VERSION
    - export ARG_GITALY_SERVER_VERSION=$GITALY_SERVER_VERSION
    - export DOCKER_TAG=$GITALY_SERVER_VERSION
    - install -Dm0644 lib/* -t gitaly/build/lib/
    - entrypoint

build:gitaly:
  extends: [.build-image, .component:gitaly]
  stage: build
  variables:
    EXEC_COMMAND: build
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "false" || $CI_MERGE_REQUEST_IID
      changes:
        paths:
          - .gitlab-ci.yml
          - overlay/**/*
          - gitaly/**/*
          - lib/**/*
          - build-args.env
          - VERSIONS

publish:gitaly:
  extends: [.build-image, .rules:publish, .component:gitaly]
  stage: publish
  variables:
    EXEC_COMMAND: publish

publish:gitaly-next:
  extends: [.build-image, .component:gitaly]
  stage: publish
  variables:
    EXEC_COMMAND: publish
    DOCKER_TAG: next
  rules:
    - if: $CI_COMMIT_REF_NAME == "next"

.component:gitlab:
  variables:
    PUBLISH_CI_IMAGE: YesPlease
    MIRROR_DOCKER_HUB: YesPlease
    EXEC_SH: YesPlease
    ARG_REGISTRY_IMAGE_BASE: $CI_REGISTRY_IMAGE
    ARG_CI_TAG: ci-$CI_COMMIT_REF_SLUG
  script:
    - source ./VERSIONS
    - source ./build-args.env
    - export ARG_ALPINE_VERSION=$ALPINE_VERSION
    - export ARG_RUBY_VERSION=$RUBY_VERSION
    - export ARG_GITLAB_VERSION=$GITLAB_VERSION
    - export ARG_GITALY_SERVER_VERSION=$GITALY_SERVER_VERSION
    - export ARG_GITLAB_SHELL_VERSION=$GITLAB_SHELL_VERSION
    - export DOCKER_TAG=$GITLAB_VERSION
    - install -Dm0644 lib/* -t overlay/usr/local/lib/
    - entrypoint

build:gitlab:
  extends: [.build-image, .component:gitlab]
  stage: build
  variables:
    EXEC_COMMAND: build
  needs:
    - job: build:gitlab-shell
    - job: build:gitaly
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "false" || $CI_MERGE_REQUEST_IID
      changes:
        paths:
          - .gitlab-ci.yml
          - Dockerfile
          - overlay/**/*
          - lib/**/*
          - build-args.env
          - VERSIONS

publish:gitlab:
  extends: [.build-image, .rules:publish, .component:gitlab]
  stage: publish
  variables:
    EXEC_COMMAND: publish

publish:gitlab-next:
  extends: [.build-image, .component:gitlab]
  stage: publish
  variables:
    EXEC_COMMAND: publish
    DOCKER_TAG: next
  rules:
    - if: $CI_COMMIT_REF_NAME == "next"

build:go-away:
  extends: [.build-image]
  stage: build
  variables:
    EXEC_COMMAND: build
    COMPONENT: go-away
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "false" || $CI_MERGE_REQUEST_IID
      changes:
        paths:
          - .gitlab-ci.yml
          - go-away/**/*

publish:go-away:
  extends: [.build-image]
  stage: publish
  image: registry.alpinelinux.org/alpine/infra/docker/exec/docker-image
  script: [pwd]
  variables:
    EXEC_COMMAND: publish
    COMPONENT: go-away
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /.*-stable$/
      changes:
        paths:
          - go-away/**/*
