ARG ALPINE_VERSION
ARG RUBY_VERSION
ARG GITLAB_SHELL_VERSION
ARG GITALY_SERVER_VERSION
ARG REGISTRY_IMAGE_BASE="alpinelinux"
ARG CI_TAG
ARG GITLAB_SHELL_TAG=${CI_TAG:-$GITLAB_SHELL_VERSION}
ARG GITALY_SERVER_TAG=${CI_TAG:-$GITALY_SERVER_VERSION}
FROM $REGISTRY_IMAGE_BASE/gitlab-shell:${GITLAB_SHELL_TAG} AS gitlab-shell
FROM $REGISTRY_IMAGE_BASE/gitaly:${GITALY_SERVER_TAG} AS gitaly

FROM ruby:$RUBY_VERSION-alpine$ALPINE_VERSION

ARG GITLAB_VERSION
ENV GITLAB_VERSION=$GITLAB_VERSION

COPY overlay /
COPY --from=gitlab-shell /home/git/gitlab-shell /home/git/gitlab-shell
COPY --from=gitaly /usr/local/bin/gitaly-backup /usr/local/bin/gitaly-backup

RUN setup.sh

EXPOSE 80

ENTRYPOINT [ "entrypoint.sh" ]

CMD [ "start" ]
