#!/bin/sh

s6-svwait -t 5000 -u /run/s6/sidekiq
echo "Starting workhorse.."
exec 2>&1
cd /home/git/gitlab
su-exec git gitlab-workhorse \
	-authSocket /home/git/gitlab/tmp/sockets/gitlab.socket \
	-documentRoot /home/git/gitlab/public \
	-listenAddr 0.0.0.0:8181 \
	-config /etc/gitlab/workhorse/config.toml \
	-apiCiLongPollingDuration 50s

